repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
      always_run: true
      args: [--line-length, "79"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
    -   id: flake8
        args: [--ignore, "F401,W503"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: fix-encoding-pragma
        args: [--remove]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports

default_language_version:
    python: python3.8
